// <auto-generated />
using Financas_api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Financas_api.Migrations
{
    [DbContext(typeof(FinancaContext))]
    [Migration("20191008235113_Alteracoes_fundos")]
    partial class Alteracoes_fundos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Financas_api.Model.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int?>("ProprietarioId");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("Financas_api.Model.FundoDeInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ANBIMA");

                    b.Property<long>("CNPJ");

                    b.Property<int?>("CarteiraId");

                    b.Property<string>("ISIN");

                    b.Property<string>("Nome");

                    b.Property<decimal>("TxAdministracao");

                    b.Property<decimal>("TxImpRenda");

                    b.Property<decimal>("TxPerformance");

                    b.Property<decimal>("TxResgate");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraId");

                    b.ToTable("Fundos");
                });

            modelBuilder.Entity("Financas_api.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Financas_api.Model.Carteira", b =>
                {
                    b.HasOne("Financas_api.Model.Pessoa", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId");
                });

            modelBuilder.Entity("Financas_api.Model.FundoDeInvestimento", b =>
                {
                    b.HasOne("Financas_api.Model.Carteira")
                        .WithMany("Fundos")
                        .HasForeignKey("CarteiraId");
                });
#pragma warning restore 612, 618
        }
    }
}
